#    ____  _____  ____  _    __               _  __ __
#   / __ \|__  / / __ \| |  / /____ _ ____   (_)/ // /____ _
#  / /_/ / /_ < / / / /| | / // __ `// __ \ / // // // __ `/
# / _, _/___/ // /_/ / | |/ // /_/ // / / // // // // /_/ /
#/_/ |_|/____//_____/  |___/ \__,_//_/ /_//_//_//_/ \__,_/
#
noteLimit: 10
defaultMessagePing: true
sleepCooldown: 300
sleepPercent: 51
afkTimer: 300

enableDatabase: true
databaseUser: ''
databasePass: ''
databaseName: ''
databaseHost: ''

defaultMessageSound: 'BLOCK_NOTE_BLOCK_BELL'
defaultMessageSoundPitch: 2
messageTag: '&8[&6Messages&8]'
replyTag: '&8[&6Reply&8]'
messagePingTag: '&8[&6Message Ping&8]'